---
title: "Types of Usage of Funding in Each Country"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
TB_usage2 = read.csv("./data/TB_expenditure_utilisation.csv")
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(reshape2)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

TB_usage2 = read.csv("./data/TB_expenditure_utilisation.csv")

table(TB_usage2$g_whoregion) #We will use WPR(Western Pacific) , SEA(South East Asia)
TB_usage2 = TB_usage2 %>%
  select(
    country, year, g_whoregion,hospd_mdr_dur,
    rcvd_fld, rcvd_lab, rcvd_mdrmgt, rcvd_orsrvy, rcvd_oth, rcvd_patsup, 
    rcvd_prog, rcvd_sld, rcvd_staff, rcvd_tbhiv, rcvd_tpt
  ) %>%
  filter(
    g_whoregion == "WPR" | g_whoregion == "SEA"
  ) %>%
  select(-g_whoregion) %>%
  rename(
    patient = rcvd_patsup,
    staff = rcvd_staff,
    programme = rcvd_mdrmgt,
    drugs = rcvd_fld,
    other = rcvd_oth
  )

colSums(is.na(TB_usage2)) #remove rcvd_tpt because there are many NAs.

TB_usage2 = TB_usage2 %>% 
  select(-rcvd_tpt) 

colSums(is.na(TB_usage2))

TB_usage2 = TB_usage2 %>%
  na.omit(drugs)

TB_usage2 = TB_usage2[TB_usage2$country %in% names(which(table(TB_usage2$country) > 2)), ] 
#remove the data that doesn't have 2017,2018,2019
unique(TB_usage2$country)
colSums(TB_usage2 == 0)

TB_usage2 %>%
  select(-country, -year) %>%
  colMeans() %>%
  order() 
#top 5 usage type of fundings are: patient, staff, programme, drugs, other

usage_2017_top5 = TB_usage2 %>% 
  filter(year == "2017") %>%
  select(country, patient, staff, programme, drugs, other) %>%
  melt(id.vars = 'country', variable.name = 'usage_type')

usage_2018_top5 = TB_usage2 %>% 
  filter(year == "2018") %>%
  select(country, patient, staff, programme, drugs, other) %>%
  melt(id.vars = 'country', variable.name = 'usage_type')

usage_2019_top5 = TB_usage2 %>% 
  filter(year == "2019") %>%
  select(country, patient, staff, programme, drugs, other) %>%
  melt(id.vars = 'country', variable.name = 'usage_type')
```

Column {data-width=650}
-----------------------------------------------------------------------

### Types of Usage of funding in each country in 2017

```{r echo=FALSE, fig.width = 10, fig.height = 10}
ggplot(data = usage_2017_top5, aes(x = country, y = value, fill = usage_type)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Paired") +
 labs(x = "Countries") +
  scale_y_continuous(name = "US Dollars($)", labels = scales::comma) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Types of Usage of funding in each country in 2018

```{r echo=FALSE, fig.width = 10, fig.height = 10}
ggplot(data = usage_2018_top5, aes(x = country, y = value, fill = usage_type)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Paired") +
 labs(x = "Countries") +
  scale_y_continuous(name = "US Dollars($)", labels = scales::comma) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))
```

### Types of Usage of funding in each country in 2019

```{r echo=FALSE, fig.width = 10, fig.height = 10}
ggplot(data = usage_2019_top5, aes(x = country, y = value, fill = usage_type)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Paired") +
 labs(x = "Countries") +
  scale_y_continuous(name = "US Dollars($)", labels = scales::comma) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))
```

