---
title: "Mortality & Funding"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

```{r include = FALSE}
library(tidyverse)
library(gapminder)
library(echarts4r)
library(dplyr)
library(ggplot2)
library(reshape2)
library(gganimate)
library(htmlwidgets)
library(ggiraph)
library(widgetframe)
library(ggthemes)
library(plotly)
library(viridis)
library(DT)
library(gifski)
library(png)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r include = FALSE}
TB_burden = read.csv("./data/TB_burden_countries.csv")

TB_burden = TB_burden %>%
  mutate(
    e_mort_pro = as.numeric(e_mort_num)/as.numeric(e_pop_num),
    e_mort_pro_100k = as.numeric(e_mort_num)/as.numeric(e_pop_num) * 100000
  ) %>%
  select(
    country, year, e_mort_num
  )

world <- map_data("world") %>%
  filter(region != "Antarctica")
```

```{r message = FALSE, warning = FALSE, echo = FALSE}
interactive_map = TB_burden %>%
  right_join(world, by = c(country = "region")) %>%
  ggplot(aes(long, lat, group = group, fill= e_mort_num)) +
  geom_polygon(color = "white", size = 0.01) +
  theme_void() +
  scale_fill_viridis(option = "B",
                     name= "Estimated number of deaths from TB",
                     guide = guide_colorbar(
                       direction = "horizontal",
                       barheight = unit(2, units = "mm"),
                       barwidth = unit(100, units = "mm"),
                       draw.ulim = FALSE,
                       title.position = "top",
                       title.hjust = 0.5,
                       title.vjust = 0.5 )) +
  labs(title="Estimated number of deaths from TB",
       subtitle = "{current_frame}",
       caption = "Source: gapminder.org")  +
  theme(
    plot.title = element_text(size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    plot.caption = element_text(size = 8, hjust = 1),
    legend.position = "bottom") +
  coord_fixed (ratio = 1.3) +
  transition_manual(year)


animate(interactive_map, 
        fps = 10, 
        height = 500, 
        width = 700)
```


```{r echo = FALSE, message = FALSE, fig.width = 11, fig.height = 12}
TB_burden = read.csv("./data/TB_burden_countries.csv")

TB_mort =
  TB_burden %>%
  filter(country %in% c("Bangladesh", "Cambodia", "India", "Indonesia", "Lao People's Democratic Republic",
                        "Mongolia", "Myanmar", "Nepal", "Solomon Islands", "Thailand", "Timor-Leste")) %>%
  select(country, year, e_pop_num, e_mort_num) %>%
  mutate(e_mort_pro = as.numeric(e_mort_num)/as.numeric(e_pop_num)) %>%
  select(-e_pop_num, -e_mort_num) %>%
  mutate(
    year = as.numeric(year), 
    e_mort_pro = as.numeric(e_mort_pro))

p <- ggplot(data = TB_mort, aes(x = year, y = e_mort_pro, group = country)) +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = "Year", title = "Estimated proportions of death from TB in each country in 2000~2019") +
  scale_y_continuous(name = "Proportion of deaths from TB") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 1))
p + transition_reveal(year)
```

```{r message = FALSE, echo = FALSE, fig.width = 12, fig.height = 12}
TB_burden = read.csv("./data/TB_burden_countries.csv")

TB_mort =
  TB_burden %>%
  filter(country %in% c("Bangladesh", "Cambodia", "India", "Indonesia", "Lao People's Democratic Republic",
                        "Mongolia", "Myanmar", "Nepal", "Solomon Islands", "Thailand", "Timor-Leste")) %>%
  filter(year %in% c("2017", "2018", "2019")) %>%
  select(country, year, e_pop_num, e_mort_num) %>%
  mutate(e_mort_pro = as.numeric(e_mort_num)/as.numeric(e_pop_num)) %>%
  select(-e_pop_num, -e_mort_num) %>%
  mutate(
    year = as.factor(year), 
    e_mort_pro = as.numeric(e_mort_pro))


ggplot(data = TB_mort, aes(x = year, y = e_mort_pro, group = country)) +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = "Year", title = "Estimated proportions of death from TB in each country in 2017~2019") +
  scale_y_continuous(name = "Proportion of deaths from TB")
```

```{r message = FALSE, echo = FALSE, fig.width = 11, fig.height = 12}
TB_funding = read.csv("./data/TB_expenditure_utilisation.csv")

TB_tot_funding =
  TB_funding %>%
  filter(country %in% c("Bangladesh", "Cambodia", "India", "Indonesia", "Lao People's Democratic Republic",
                        "Mongolia", "Myanmar", "Nepal", "Solomon Islands", "Thailand", "Timor-Leste")) %>%
  select(country, year, rcvd_tot_sources) %>%
  rename(funding = rcvd_tot_sources) %>%
  mutate(
    year = as.factor(year), 
    funding = as.numeric(funding))


ggplot(data = TB_tot_funding, aes(x = year, y = funding, group = country)) +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = "Year", title = "Total funding received in each country in 2017~2019") +
  scale_y_continuous(name = "Funding ($)", labels = scales::comma)
```

