---
title: "Graphs for treatment data of MDR-TB & XDR-TB Patients"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

```{r include = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(reshape2)
library(gganimate)
library(htmlwidgets)
library(tidyverse)
library(ggalt)   
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
TB_outcomes = read.csv("./data/TB_outcomes.csv")
TB_usage = read.csv("./data/TB_expenditure_utilisation.csv")

TB_success = 
  TB_outcomes %>%
  filter(country %in% c("Bangladesh", "Cambodia", "India", "Indonesia", "Lao People's Democratic Republic",
                        "Mongolia", "Myanmar", "Nepal", "Solomon Islands", "Thailand", "Timor-Leste")) %>%
  select(country, year, mdr_succ, xdr_succ) %>%
  na.omit(mdr_success) %>%
  na.omit(xdr_success) %>%
  mutate(mdr_xdr_success = as.numeric(mdr_succ) + as.numeric(xdr_succ)) %>%
  select(-mdr_succ, -xdr_succ) %>%
  mutate(
    year = as.integer(year), 
    mdr_xdr_success = as.integer(mdr_xdr_success))
  
p <- ggplot(data = TB_success, aes(x = year, y = mdr_xdr_success, group = country)) +
  geom_line(aes(color = country)) +
  geom_point(aes(color = country)) +
  labs(x = "Year", title = "Number of MDR-TB and XDR-TB patients who completed treatments or were cured") +
  scale_y_continuous(name = "Number of patients") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 1))

p + transition_reveal(year)
```

```{r tidy data, include = FALSE, echo = FALSE, message = FALSE}
table(TB_usage$g_whoregion) #We will use WPR(Western Pacific) , SEA(South East Asia)
TB_usage = TB_usage %>%
  select(
    country, year, g_whoregion,hospd_mdr_dur,
    rcvd_fld, rcvd_lab, rcvd_mdrmgt, rcvd_orsrvy, rcvd_oth, rcvd_patsup, 
    rcvd_prog, rcvd_sld, rcvd_staff, rcvd_tbhiv, rcvd_tpt
  ) %>%
  filter(
    g_whoregion == "WPR" | g_whoregion == "SEA"
  ) %>%
  select(-g_whoregion)

colSums(is.na(TB_usage)) #remove rcvd_tpt because there are many NAs.

TB_usage = TB_usage %>% 
  select(-rcvd_tpt) 

colSums(is.na(TB_usage))

TB_usage = TB_usage %>%
  na.omit(rcvd_fld)

TB_usage = TB_usage[TB_usage$country %in% names(which(table(TB_usage$country) > 2)), ] 
#remove the data that doesn't have 2017,2018,2019
```


```{r Variable:Types of Usage funding in each country in 2017-2019, include=FALSE, echo = FALSE, message = FALSE}
unique(TB_usage$country)
colSums(TB_usage == 0)

TB_usage %>%
  select(-country, -year) %>%
  colMeans() %>%
  order() 
#top 5 usage type of fundings are: rcvd_patsup, rcvd_staff, rcvd_mdrmgt, rcvd_fld, rcvd_oth

usage_2017_top5 = TB_usage %>% 
  filter(year == "2017") %>%
  select(country, rcvd_patsup, rcvd_staff, rcvd_mdrmgt, rcvd_fld, rcvd_oth) %>%
  melt(id.vars = 'country', variable.name = 'usage_type')

usage_2018_top5 = TB_usage %>% 
  filter(year == "2018") %>%
  select(country, rcvd_patsup, rcvd_staff, rcvd_mdrmgt, rcvd_fld, rcvd_oth) %>%
  melt(id.vars = 'country', variable.name = 'usage_type')

usage_2019_top5 = TB_usage %>% 
  filter(year == "2019") %>%
  select(country, rcvd_patsup, rcvd_staff, rcvd_mdrmgt, rcvd_fld, rcvd_oth) %>%
  melt(id.vars = 'country', variable.name = 'usage_type')
```


# Estimated average duration of stay if patients starting MDR-TB/XDR-TB treatment are hospitalized (days)
```{r include=FALSE}
TB_duration_2017 = TB_usage %>%
  filter(year == "2017") %>%
  mutate(hospd_2017 = hospd_mdr_dur) %>%
  select(country, hospd_2017)

TB_duration_2018 = TB_usage %>%
  filter(year == "2018") %>%
  mutate(hospd_2018 = hospd_mdr_dur) %>%
  select(country, hospd_2018)

TB_duration_2019 = TB_usage %>%
  filter(year == "2019") %>%
  mutate(hospd_2019 = hospd_mdr_dur) %>%
  select(country, hospd_2019)

TB_duration = full_join(inner_join(TB_duration_2017, TB_duration_2018), TB_duration_2019)
```

```{r echo=FALSE}
TB_duration = full_join(inner_join(TB_duration_2017, TB_duration_2018), TB_duration_2019)

ggplot() +
  geom_segment(data=TB_duration, aes(y = country, yend = country, x = 0, xend = .5), 
               color = "#b2b2b2", size = 0.15) + 
  geom_dumbbell(data = TB_duration, aes(y=country, x = hospd_2017, xend = hospd_2019),
                size = 1.5, color = "#b2b2b2", size_x = 3, size_xend = 3, colour_x = "red",
                colour_xend = "blue") +
  labs(x = "Estimated average duration of stay in hospitals(days)", y = "Country", 
       title = "Estimated average duration of stay if patients starting MDR-TB/XDR-TB
       treatment are hospitalized (days)") +
  theme(axis.text.y = element_text(angle = 45, vjust = 0.5, hjust = 1))


ggplot(data = TB_usage, aes(x = country, y = hospd_mdr_dur, fill = year)) +
  geom_bar(stat = "identity") +
  labs(x = "Estimated average duration of stay in hospitals(days)", y = "Country", 
       title = "Estimated average duration of stay if patients starting MDR-TB/XDR-TB
       treatment are hospitalized (days)") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1)) 
```

