---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Motivation

According to CDC, TB infects more than 10 million people each year and is the leading infectious disease killer. In 2018, 1.7 billion people were infected by Tuberculosis bacteria, which is around 23% of the world's population. In addition, TB is becoming a more serious infectious disease as 
approximately 20% of TB cases around the world are resistant to anti-TB drugs. This is problematic because treatments for such MDR-TB(multi-drug resistant TB) and XDR-TB(extensively drug resistant TB) cases are limited, often toxic, and expensive. Thus, we wanted to learn more about TB cases around the world and whether national fundings are related with TB mortality cases around the world. Moreover, given the threat of drug resistant TB cases, we wanted to look more into treatment statuses for MDR-TB and XDR-TB patients. 


# Related work

The following resources are some of the inspirations of this project. 

* [CDC MDR-TB](https://www.cdc.gov/tb/publications/factsheets/drtb/mdrtb.htm)

* [US Government and Global Tuberculosis Efforts](https://www.kff.org/global-health-policy/fact-sheet/the-u-s-government-and-global-tuberculosis-efforts/)

* [Report Warns of rise in Drug-resistant Tuberculosis](https://www.cidrap.umn.edu/news-perspective/2017/03/report-warns-rise-drug-resistant-tuberculosis)

* [Tuberculosis: A Global Health Problem](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2980871/pdf/jhpn0028-0111.pdf)


# Questions throughout the project

Our main questions were constant throughout the project, but some additional questions arose in the course of our data analyses. Initially, we intended to examine TB mortality rates across countries in all continents from 2000 to 2019, but due to lack of pertinent data, we focused on examining TB mortality rates in 11 specific countries in the Asia region. In these countries, we were curious if total national TB funding received in the last three years have had any association with the TB mortality rates in these last three years. Naturally, we also wanted to learn more about the usages of these fundings in each country. 
Not only that, one of our initial areas of interest was examining around how many MDR-TB and XDR-TB patients complete successful treatment each year. So, we wanted to do so for the years from 2000 to 2019 for the countries that we have selected. After noticing that the number of such patients seem to have been slightly increasing in recent years, we were curious if the average duration of stay in hospitals for such patients show any trends in recent years. 
After doing so, we became more interested in performing some regression analysis to see if the average duration of stay in hospitals for these patients can be predicted by various types of TB fundings. This is a slight change from our initial intent of performing regression analysis on TB fundings with TB mortality rates, since this regression did not seem to be statistically significant and also seemed quite broad of a relationship. Thus, we decided to focus more on examining and predicting the relationship between average duration of hospital stay for MDR-TB and XDR-TB patients and various types of national TB fundings. 

# Data

The source of our three main datasets and data dictionary are from the World Health Organization. 
They can be accessed [here](https://www.who.int/teams/global-tuberculosis-programme/data).

Variables that we have used are:

* **e_mort_num**: Estimated number of deaths from TB
* **e_pop_num** : Estimated total population number
* **mdr_succ** : Outcomes for MDR-TB cases: treatment success(cured or treatment completed)
* **xdr_succ** : Outcomes for XDR-TB cases: treatment success(cured or treatment completed)
* **country** : Country
* **year** : Year of the data
* **patient**: Funding received for patient support (US Dollars)
* **staff**: Funding received for National TB Programme staff (central unit staff and subnational TB staff)  (US Dollars)
* **programme**: Funding received for programme costs to treat drug-resistant TB (US Dollars)
* **drugs**: Funding received for drugs to treat drug-susceptible TB (US Dollars)
* **other**: Funding received for all other budget line items (US Dollars)
* **hospd_mdr_dur**: Estimated average duration of stay if patients starting MDR-TB/XDR-TB treatment are hospitalized (days)


# Exploratory & Additional Analysis
### Mortality & Funding 
Question: What are the estimated number of deaths from TB around the world from 2000~2019?
          Are there any countries with high estimated number of deaths from TB? <br/>
        : Are there any trends in estimated proportions of death from TB in various countries
          in these years and also in the recent three years?<br/>
        : What are the trends in total TB funding received in these countries in the recent
          three years? Do these trends show any association with the trends in estimated
          proportions of death from TB in these countries in the recent three years? 

### Funding Usages
Question: What are the top 5 areas that the national TB fundings received were allocated to in each country in each year from 2017~2019? Are there any trends per country and across the countries? Do these trends seem to change over the years? 

### TB Hospitalization
Question: What were the number of MDR-TB and XDR-TB patients who completed treatment or were cured in the last 19 years? Are there any trends?
:What were the estimated duration of stay if these patients starting treatment were hospitalized in 2017~2019? Are there any relationships between the number of these patients who completed treatment and the estimated duration of hospital stay for these patients receiving treatment? 

### Regression Analysis
After we plotted the density graph, we noticed it was heavily right skewed. So, doing a log transformation made the density look more normal. Thus, doing a log linear regression helped to predict the average hospital stay in 2020.
Based on the normal transformation, the model we fit was:
$$log(average\ duration\ of\ stay\ for\ treatment) = \beta_0 + \beta_1 year + \beta_2 patient  + \beta_3 staff + \beta_4 programme + \beta_5 drugs + \beta_6 other$$

With the regression analysis, we can predict the estimated average duration of stay if patients starting MDR-TB/XDR-TB treatment are hospitalized, and We used the top 5 usages of funding and year. We have also included the interaction between **patient** and **staff** because there could be a possible relationship that the funding for patient support and different national TB programme staffs can affect durations of hospital stay.

However, with the countries that we selected, there was not enough significant data to conduct multiple linear regression.
Thus, we haved used all the countries in the datasets for increased accuracy and significance. After conducting such linear regression including all countries, we could see that F-statistic is 911.8 with the p-value of less than 0.05.
We also conducted the ANOVA test to see if the interaction variable is crucial or not, and the result showed that it is significant.
Therefore, we can use this regression to predict the average length of hospital stay for MDR-TB and XDR-TB patients getting treatment in 2020.

# Findings & Discussion
After the regression, the following regression is:
$$log(average\ duration\ of\ stay\ for\ treatment) = $$
$$- 130.8329 + 0.06694 year + 0.00000001176 patient  + 0.00000000155 staff $$
$$+ 0.0000001160 programme - 0.00000013128 drugs - 0.00000000898 other$$

Thus, when plugging in the average funding for each variable, we are  95% confident that in 2020, the average stay at hospitals for MDR-TB and XDR-TB patients receiving treatments will fall between **-0.3268** and **5.75** days.
